### ISSUE TITLE
[Feature Request] "Array's Add Element"-sized button

### ISSUE THREAD

**Issue by etherealxx** [domske/godot-addon-simple-tool-button#1]
First thing first, amazing addon.
I noticed that the button's width is as long as the node's category (see image below, the `Save Image` button). While other Inspector button like the one that shows when adding an item to an Array (the `+ Add Element` button) are usually more compact in the middle.
![image](https://github.com/user-attachments/assets/6a25b59e-84db-46bc-a527-6b76f274a312)
Maybe add the size as an option, like with your Advanced Button syntax.

**Comment by etherealxx** [comment]
another reference, [Shaker](https://github.com/Eneskp3441/Shaker) addon (MIT) has this button
![image](https://github.com/user-attachments/assets/17062d3f-983c-4624-8af3-6be228e7604e)

**Comment by domske** [comment]
Thanks. Personally, I like the full width button. But yes, it can look weird on a very wide inspector panel. Hard to recognize as a button. This is the default behavior when adding Godot's built-in button to the inspector. It looks different than the other official inspector buttons. Anyway... I'll check later to see if I can do something about it. I already have some ideas on how to make it look more like a button and have multiple buttons in a row.

**Comment by domske** [comment]
Ok, done. Version 1.3.0 is now available. Please check the readme.md. For example:

```gdscript
@export var btn_mutiple_buttons: Array:
  get: return [
    {
      "text": "Play",
      "icon": "Play",
      "click": func(): play(),
    },
    {
      "text": "Stop",
      "icon": "Stop",
      "click": func(): stop(),
    }
  ]
```

The advanced buttons now appears not in full width. But you can add the `fill` property to use the available width. And you can use multiple buttons in row. I also use the getter to workaround the Godot issue of remaining values ​​in the scene. Otherwise, you need to rename the variable name to update changes. With `get` you can change properties without rename.
