### ISSUE TITLE
Trying to assign value of type 'TypeName' to a variable of type 'Node'.

### ISSUE THREAD

**Issue by anatolbogun** [domske/godot-addon-simple-tool-button#2]
Hi, thank you so much for this very useful addon! I worked with boolean checkboxes before, but a UI button can sometimes make a lot more sense.

I occasionally get an error in the output console, possibly when I use some not-so-common `@export` variable types like a `Curve`, e.g. `@export var tree_density_by_z: Curve`.

>   res://addons/simple_tool_button/inspector.gd:24 - Trying to assign value of type 'Curve' to a variable of type 'Node'.

I could make this error go away by changing the type of `current_node` from `Node` to `Object` on [line 21](https://github.com/domske/godot-addon-simple-tool-button/blob/main/addons/simple_tool_button/inspector.gd#L21). The addon still seems to work as expected.

The script also complained about some indentation inconsistencies (mixed spaces and tabs). I think I fixed it up (no code changes here except the `Node` to `Object`, just all indentations changed to tabs. Feel free to use it – or not: [simple_tool_button.zip](https://github.com/user-attachments/files/17159091/simple_tool_button.zip)

(I'm currently using `Godot v4.4.dev2.official [97ef3c837]`.)

**Comment by domske** [comment]
Thanks for the report. I'll check it out. I expected everything in the scene to be based on `Node`. It seems I have to check the type first and handle it as Variant first. Or just `Object`, because this is the very base class for all other classes in the engine. In your case, `Curve` does not extend from `Node`, but `Object` ([docs](https://docs.godotengine.org/en/4.3/classes/class_curve.html)). No problem, I'll fix it...

About indentation: I don't see any mixed types. Just spaces. I used 2 spaces as indentation. But I think I go back to real tabs and set the rendered size to 2 spaces. It seems that Godot (and Python) works better with tabs than with spaces. In e.g. TypeScript I prefer 2 space indent for several reasons. It's annoying that many editors (incl. GitHub, GitLab, etc.) renders tabs with ridiculous 8 spaces width. It's hard to read, when e.g. review directly in GitHub. Anyway... ^^

Will be fixed in 1.4.1
